### ISSUE TITLE
Teleop

### ISSUE THREAD

**Issue by JustBenj** [osu-uwrt/riptide_software#75]
The teleop stack needs updated to be compatible with the latest code. It hasn't been tested in ages, but would be useful for collecting video at the pool without needing the control stack to be fully functional.

We should be able to drive the robot without going through the attitude or depth controllers.

**Comment by tsender** [comment]
Nah, the new PS3 controller uses the controllers, since they work.

**Comment by JustBenj** [comment]
Not a bad idea to keep a node around for "open-loop PS3 control", for when one of our sensors inevitably stops working or our mechanical design changes and the controllers need re-tuned
